### ISSUE TITLE
strange keybinding in Sage-doc mode

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage-shell-mode#25]
I just noticed that the keybinding for `sage-shell:send-doctest` in `Sage-doc` mode is `C-c C-j`, rather than `C-c C-d`, which is surprising...

**Comment by stakemori** [comment]
Thank you for reporting. I just bind `C-c C-d` to `sage-shell:send-doctest` in `doc-mode` in b1a4f53d7f7ea6d1d67c0f61d527f4efa92d187b.
