### ISSUE TITLE
uniq is deprecated

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage-shell-mode#42]
As of sagemath 8.7, `sage.misc.all.uniq` is deprecated, and should be replaced with `sorted(set(x))`.  It is used only once, one line 177 in `https://github.com/sagemath/sage-shell-mode/blob/master/emacs_sage_shell.py` - the import on line 30 should then also be removed.

Thanks for all your work!

**Comment by fchapoton** [comment]
merged
