### ISSUE TITLE
Sage mode inserts a lot of space when return is pressed in Emacs.

### ISSUE THREAD

**Issue by simurgh9** [sagemath/sage-shell-mode#52]
I am not sure what is causing it but each time I press enter this happens,

![Screenshot_20200713_033428](https://user-images.githubusercontent.com/43047754/87282553-02504e80-c4ba-11ea-823a-e81a7175f300.png)

**Comment by reverland** [comment]
me too..and i'm curious about this now..

**Comment by simurgh9** [comment]
Yeap! That did the trick. For other readers, run `sudo emacs /usr/bin/sage` to edit the file. You'll need to change the line `exec sage-ipython "$@" -i` to `exec sage-ipython "$@" --simple-prompt -i` as shown in @reverland's reply.
