### ISSUE TITLE
Incorrect postioning of prompt

### ISSUE THREAD

**Issue by balbirthomas** [sagemath/sage-shell-mode#56]
After clean install of Sage 9.0 on Ubuntu 20.04 and cloning the latest sage-shell-mode git repository I find that running sage within Emacs 26.3 results in the prompt being positioned to the far right of the screen with preceding spaces. The first command line input and output also vanishes from the screen. Though for subsequent commands input and output are shown. However after each command the cursor is positioned to the far right of the screen., with preceding spaces. Attached is the simple `.emacs` file used and a screenshot.  The screenshot shows the state of the screen after launching sage within emacs using `M-x run-sage` and then executing the command `diff(x^3,x)`. Please do let me know what further information you may need.
[dotemacs.txt](https://github.com/sagemath/sage-shell-mode/files/5737171/dotemacs.txt)
![Screenshot](https://user-images.githubusercontent.com/1672069/103037967-0dc59c80-4565-11eb-8117-a618566e86f3.png)

**Comment by EmmanuelCharpentier** [comment]
This is issue #53 for which a PR has been proposed on Aug 25, still unreviewed on Dec 25.... In the interim, feel free t use my [fork](https://github.com/EmmanuelCharpentier/sage-shell-mode).

**Comment by balbirthomas** [comment]
Thank you for your response. Indeed the issue seems to be the same. In view of this fact I am closing this bug. However it seems like this is a solution going forward for newer versions of sage (>9.2) which accept `--simple-prompt` option. 

I did try to use the latest git master branch of `sage-shell-mode` (this) repository with your patches merged in. I can confirm they do not fix the issue with the version of sage (Sage 9.0 using Python 3.8.5 and IPython 7.13.0) that ships packaged with Ubuntu 20.04.
