### ISSUE TITLE
tex-buf.el has been merged into tex.el

### ISSUE THREAD

**Issue by tarsius** [sagemath/sage-shell-mode#63]
I've noticed this because I maintain the [Emacsmirror](https://emacsmirror.org) and the tools, that I use to do so, inform me when a dependency of a mirrored package isn't satisfied (anymore).

In `auctex` [`tex-buf.el` was merged into `tex.el`](https://github.com/emacsmirror/auctex/commit/4b1c7015ae77b88832af35510232e1a1b716da3a) but your package still `require`s `tex-buf`. You can probably fix this by depending on `tex` instead, or if you already do that by dropping the additional `(require 'tex-buf)`.

**Comment by EmmanuelCharpentier** [comment]
A workaround is to add `(provide 'tex-buf)` in the relevant part of your `.emacs`.

Hint given in an `auctex-latexmk` [issue](https://github.com/tom-tan/auctex-latexmk/issues/44).

I'll submit the relevant patch soon.

**Comment by EmmanuelCharpentier** [comment]
> I'll submit the relevant patch soon.

Done, pull request emitted.

**Comment by tarsius** [comment]
The pull-request is #65.
